services:
  zina-gpt:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: zina-gpt
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zina-network

networks:
  zina-network:
    driver: bridge 